version: '3'
 
services:
  elasticsearch:
    build : ./elasticsearch
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    networks:
      - lognet
    #data persitence
    volumes:
      - esdata:/usr/share/elasticsearch/data
 
  kibana:
    build : ./kibana
    container_name: kibana
    environment:
      SERVER_NAME : kibana
      #accessing elasticsearch url and port inside the subnet
      ELASTICSEARCH_URL : http://elasticsearch:9200
    networks:
      - lognet

  proxy:
    build : ./nginx
    container_name : proxy
    #the log server is accessible by 8080 port and redirected to 80
    ports:
      - "8080:80"
    networks:
      - lognet
 
volumes:
   esdata:
     driver: local
 
networks:
   lognet: