input {
    beats {
        port => "5044"
    }
}
filter {

}
output {
    stdout { codec => rubydebug }
    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "browsers-%{+YYYY.MM.dd}"
        }
    }
}